<?php

namespace Boutique\ProduitsBundle\Repository;

/**
 * ImagePrincipaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagePrincipaleRepository extends \Doctrine\ORM\EntityRepository
{
}
